baseurl = "http://rrra.org"
languageCode = "en-us"
title = "Red River Radio Amateurs"

theme = "twentyfourteen"
Paginate = 10
newcontenteditor = "vim"

description = "News from the Red River Radio Amateurs"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
	email = "webmaster@rrra.org"
	name = "K0STK"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  dates = "dates"
  ncs = "ncs"
  authors = "authors"

[params]
	specials = [ "NCS Schedule","Public Service","Social" ]

[permalinks]
	post = "/post/:year/:month/:day/:slug/"
	calendar = "/cal/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Calendar"
    identifier = "calendar"
    url = "/calendar/0/"

[[menu.main]]
    name = "Files"
    identifier = "files"
    url = "/links/"

[[menu.main]]
    name = "SK"
    identifier = "sk"
    url = "/sk/"
