baseurl = "http://rrra.org"
languageCode = "en-us"
title = "Red River Radio Amateurs"

theme = "twentyfourteen"
Paginate = 10
newcontenteditor = "vim"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  dates = "dates"
  ncs = "ncs"

[permalinks]
	post = "/post/:year/:month/:day/:slug/"
	calendar = "/cal/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Calendar"
    identifier = "calendar"
    url = "/calendar/0/"

[[menu.main]]
    name = "Files"
    identifier = "files"
    url = "/links/"

[[menu.main]]
    name = "SK"
    identifier = "sk"
    url = "/sk/"
