baseurl = "http://rrra.org"
languageCode = "en-us"
title = "Red River Radio Amateurs"

theme = "twentyfourteen"
Paginate = 10
newcontenteditor = "vim"

description = "News from the Red River Radio Amateurs"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
	email = "webmaster@rrra.org"
	name = "K0STK"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  dates = "dates"
  ncs = "ncs"
  authors = "authors"

[permalinks]
	post = "/post/:year/:month/:day/:slug/"
	calendar = "/cal/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Calendar"
    identifier = "calendar"
    url = "/calendar/0/"

[[menu.main]]
    name = "Files"
    identifier = "files"
    url = "/links/"

[[menu.main]]
    name = "SK"
    identifier = "sk"
    url = "/sk/"

[params]
	silentkeybase = "http://silentkeyhq.com/main.php4?p=bin/NSKALookup.php4&dlnk=&"

[params.categories]

[params.categories.education]
	description = "Blog posts about the activities of the RRRA Education Committee and educational topics of general interest."

[params.categories.hamfest]
	description = "Blog posts about RRRA Hamfests and the activities of the RRRA Hamfest Committee."

[params.categories.license-testing]
	description = "Blog posts about the activities of the RRRA Volunteer Examiner (VE) Committee and topics related to FCC license testing. Please visit the [License Testing Dates](/dates/license-testing/) page for information about what to bring to a testing session and how to find out when your license is granted."

[params.categories.minutes]
	description = "Minutes recorded by the RRRA Secretary during the club's monthly business meetings. The minutes posted here are converted from the original source documents to Markdown; the source documents are archived on the [RRRA file sharing server](http://cloud.rrra.org) in the *Secretary's Reports* folder."

[params.categories.outreach]
	description = "Blog posts about RRRA activities intended to promote or advocate for Amateur Radio to the public, our government, and our served agencies."

[params.categories.public-service]
  description = 'Blog posts about the activities of the RRRA ARES Committee and the "voluntary noncommercial communication service, particularly with respect to providing emergency communications" (*["Amateur Radio Service." 47 "CFR" 97.1(a). 2016.](http://www.ecfr.gov/cgi-bin/text-idx?c=ecfr&rgn=div5&view=text&node=47:5.0.1.1.6&idno=47#se47.5.97_11)*), provided to the public by Amateur Radio operators.' 

[params.categories.social]
	description = "Blog posts about RRRA social activites."

[params.categories.technical]
  description = "Blog posts about the activities of the RRRA Technical Committee and the equipment/systems they maintain. This archive also includes blog posts about technical topics of general interest."

